version: '2'

services:
  nginx-lb:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 6M

  homepage:
    build: .
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=dj26.naver.com
      - VIRTUAL_PORT=80
    deploy:
      mode: replicated
      replicas: 1 
      resources: 
        limits:
          cpus: '0.02'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 6M
