# fly.toml app configuration file generated for black-shadow-4405 on 2023-10-20T16:27:27+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "black-shadow-4405"
primary_region = "nrt"

[build]
  image = "nginx"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
